# Generated by Django 5.0.6 on 2024-12-04 21:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(choices=[('No Captado', 'No Captado'), ('Suscrito', 'Suscrito'), ('Suscrito-Activo', 'Suscrito-Activo'), ('Activo', 'Activo'), ('Inactivo', 'Inactivo'), ('Captado Rechazado', 'Captado Rechazado')], default='No Captado', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('empresa_pagina', models.CharField(blank=True, max_length=100, null=True)),
                ('correo', models.EmailField(max_length=255)),
                ('numero_contacto', models.CharField(max_length=20)),
                ('proyecto', models.TextField()),
                ('estado', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='webpage.estado')),
                ('plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='webpage.plan')),
            ],
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webpage.cliente')),
            ],
        ),
    ]
