# Generated by Django 5.0.6 on 2024-12-04 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='precio',
            field=models.PositiveIntegerField(),
        ),
    ]
