# Generated by Django 5.0.6 on 2024-12-04 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpage', '0002_alter_plan_precio'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='precio_anual',
            field=models.PositiveIntegerField(default=1000),
            preserve_default=False,
        ),
    ]
