# Generated by Django 5.0.6 on 2024-12-05 02:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpage', '0003_plan_precio_anual'),
    ]

    operations = [
        migrations.CreateModel(
            name='CodigoDescuento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50, unique=True)),
                ('descripcion', models.CharField(blank=True, max_length=255, null=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webpage.plan')),
            ],
        ),
    ]
